name: Drugable
packages:
  Narcos:
    path: ../Narcos
targets:
  Drugable:
    type: application
    sources: Sources
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortraitUpsideDown]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSupportsIndirectInputEvents: true
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        NSAccentColorName: AccentColor
    platform: iOS
    deploymentTarget:
      iOS: 14.0
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        PRODUCT_BUNDLE_IDENTIFIER: com.Drugable
        DEVELOPMENT_TEAM: 3Q2494254L
        MARKETING_VERSION: 0.1
        CURRENT_PROJECT_VERSION: 0.1.0
    dependencies:
      - package: Narcos
    preBuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrect
                swiftlint lint
        name: BuildTools
  DrugableTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests
    dependencies:
      - target: Drugable
    info:
      path: Tests/Info.plist
